### ISSUE TITLE
Add a control to show sub on mobile by default

### ISSUE THREAD

**Issue by MartyFly** [sarah-coding/mega-menu-pro-for-elementor#5]
My primary items (product categories) are in a submenu which feels natural on the desktop. On mobile, I find submenus much less intuitive.

Would it be possible to allow these to be always open? Allowing primary content to show straight away on mobile?

**Comment by sarah-coding** [comment]
Hi Marty, can I have your site address to take a close look? I can't figure out what you want.

**Comment by MartyFly** [comment]
Hi Sarah
I have attached a couple of screenshots. The Mobile-Desired.jpg file
displays the way I would like the mobile menu to open with the submenu for
PRODUCTS already showing (so that the user doesn't have to click the caret
to view it).
You can view this development site at: https://hmonks.co.uk/shop/
Thanks
Marty

**Comment by sarah-coding** [comment]
Hi Marty,

I can't find any attachment both in my mail and here but i think i got what you want.

You want to display mega panel of the "Products" menu item on mobile by default (no need to click on the sub indicator icon), right? Like this: https://prnt.sc/tv11ii

If that's what you want, please confirm me again. I will find the best way to archive that ASAP.

**Comment by MartyFly** [comment]
Yes, spot on! :)

**Comment by MartyFly** [comment]
Exactly right! - on mobile (and tablet)

**Comment by sarah-coding** [comment]
Hi Marty,

I added a new control which allows you to archive that.

First, replace the current version with this new version of the plugin:
https://www.dropbox.com/s/cxs3olpynm1tcf6/mega-menu-pro-for-elementor.zip?dl=0

Then, make sure to choose "Yes" when editing the "Products" menu item. Like
this: https://prnt.sc/tv1x5k

Kind regards, Sarah

**Comment by sarah-coding** [comment]
Hi Marty,

What is your email address? I need to send you the newest version of the
plugin privately!

**Comment by MartyFly** [comment]
Hi Sarah
Sorry for delay - I was travelling
martinjfnorton@gmail.com - does it come with a switch for tablet also?
Thanks
Martin
