### ISSUE TITLE
[BUG] Mobile Menu Dropdown immediately closes when a user scrolls

### ISSUE THREAD

**Issue by SaltedLevity** [sarah-coding/mega-menu-pro-for-elementor#7]
**Describe the bug**
When the mobile menu is set to Layout: Dropdown, and Dropdown Overlap and Dropdown Full Width are both set to Yes, on a touch device the menu will immediately collapse when a user scrolls. This creates an issue when the dropdown menu (or its submenu) is longer than the device screen, a user can't scroll to view the remaining options. 
I was able to replicate the bug on your demo site.

**To Reproduce**
1. Go to Content > Mobile Menu
2. Set the following choices:
- Layout: Dropdown
- Dropdown Overlap: Yes
- Dropdown Full Width: Yes
(unsure if it's all three causing the issues, or just the dropdown layout in general, I didn't test further)
3. On a touch screen device (e.g. cell phone) Open the Menu. Tap the first item (Mega Item [New] as you have it on the demo works). Attempt to scroll to see the rest of the submenu
4. Menu collapses before you can read or select other options

**Expected behavior**
User should be able to scroll to see the remainder of the options and/or select desired links.

**System Environment:**
 - OS: iOS 14.2
 - Browser: Safari
 - Plugin Version: On my site I'm on 1.0.4 unsure what the demo site is on
 - PHP Version: 7.4 (on my site)
 - MySQL Version: 5.7.29
 - WordPress Version: 5.6 (on my site)

**Additional context**
I only have my cell phone to test, but had the issue both on my site and on the demo site. I can provide access to my staging site if needed, but as mentioned I was able to reproduce on your main demo.

**Comment by sarah-coding** [comment]
Hi Levi, thanks for submit the bug report!

For convenient, you can send the issue directly to me at contact@sarahcoding.com.

I will check the bug and reply to you asap.

**Comment by sarah-coding** [comment]
Fixed in version 1.0.5
