### ISSUE TITLE
[FEATURE] Ability to remove link from parent level menu items

### ISSUE THREAD

**Issue by SaltedLevity** [sarah-coding/mega-menu-pro-for-elementor#8]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to remove the click-through link on some parent level menu items that don't have dedicated landing pages. I.e. if I have an "Resources" section on my site, with various types of resources under it that the mega menu shows, but _do not_ have a landing page for "Resources" I'd like the ability to disable users from being able to click right on the menu button and go to /resources. Instead the only interaction should be the show/hide of the submenu

**Describe the solution you'd like**
A quick setting or toggle to "disable parent link" for the main section - probably selectable when you edit the menu item individually?

**Describe alternatives you've considered**
- In the default Wordpress menu editor I can set a "custom link" with a url of "#" however the menu button is still clickable. Additionally this doesn't show the "Active" status if a user is on a subpage of that directory.
- Trying to override/manually disable the link myself somehow

**Additional context**
My previous (free) mega menu setup I was able to do this. I purchased your plugin in the hopes that it runs much faster on the site than my previous setup (which was Max Mega Menu by megamenu.com, which can pull in elementor sections even in the free version)

**Comment by sarah-coding** [comment]
Fixed in version 1.0.5
